<?php

namespace AppBundle\Entity;

/**
 * BallotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BallotRepository extends \Doctrine\ORM\EntityRepository
{
}
