<?php

namespace AppBundle\Entity;

/**
 * NominationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NominationRepository extends \Doctrine\ORM\EntityRepository
{
}
